layers:
  enumerate:
    type: origin
    queue: default
    plugins:
      - magpie.aws.discovery
  output:
    type: terminal
    dequeue: default
    plugins:
      - magpie.json
fifos:
  default:
    type: local
plugins:
  magpie.aws.discovery:
    enabled: true
    config:
      services:
#      By default all AWS services are scanned. Uncomment the below lines to enable only select services.
         - glacier
#         - s3
#         - rds
#         - ecs
#         - vpc
#         See the full list at https://github.com/openraven/magpie
      regions:
#        - aws-global
#        - us-east-2
#        - us-east-1
#        - us-west-1
#        - us-west-2
  magpie.json:
    enabled: false
    config:
  magpie.persist:
    enabled: true
    config:



