layers:
  enumerate:
    type: origin
    queue: default
    plugins:
      - magpie.aws.discovery
      - magpie.gcp.discovery
  output:
    type: terminal
    dequeue: default
    plugins:
      - magpie.json
      - magpie.persist
fifos:
  default:
    type: local
policies:
  root: ~/.magpie/policies
  repositories:
    - https://github.com/openraven/security-rules.git
services:
  openraven.dmap.ml:
    url: http://localhost:10234/dmap-ml/predict-annotated
plugins:
  magpie.aws.discovery:
    enabled: true
    config:
      assumedRoles:
      #      - <role arn 1>
      #      - <role arn 2>
      #      - etc...
      services:
#      By default all AWS services are scanned. Uncomment the below lines to enable only select services.
#         - ec2
#         - s3
#         - rds
#         - ecs
#         - vpc
#         See the full list at https://github.com/openraven/magpie
      regions:
#        - aws-global
#        - us-east-2
#        - us-east-1
#        - us-west-1
#        - us-west-2
      ignoredRegions:
        - fips.*
        - us-gov.*
  magpie.gcp.discovery:
    enabled: false
    config:
      services:
  magpie.json:
    enabled: true
    config:
  magpie.policy.output.json:
    enabled: false
  magpie.policy.output.csv:
    enabled: false
  magpie.policy.output.text:
    enabled: true
  magpie.persist:
    enabled: false
    config:
      hostname: localhost
      port: 5432
      schema: magpie
      databaseName: magpie
      user: magpie
      password: magpie
